### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [usmeng/news_reader#1]
@usmeng : a lot of your code files have autogenerated date comments of date *7/3/17*
Could you pls help us understand how?

**Comment by usmeng** [comment]
yes, I did the same project for practice two months ago, so I just working on the existing project and added new features. @codepathreview

**Comment by codepathreview** [comment]
:+1: Good job getting all required and a few optional stories done. A few notes after checking out the code:

* Nice to see you used action bar for searching
* Great job implementing filters as a dialog
* Properly reused the single base method in search activity to fetch results for both initial load and the pagination
* Great job using RecyclerView with StaggeredGridLayoutManager
* Consider cleaning up junk code and also refactoring code 

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation. 
/cc @codepathreview
